### ISSUE TITLE
InsecureTransportError: (insecure_transport) OAuth 2 MUST utilize https.

### ISSUE THREAD

**Issue by YinanWusoymilk** [The-Powerpuff-Girls3/slash-phase7#5]
**Describe the bug**
when I try to login with my google account, it seems like it doesn't work

Before return time:  23/11/2024 16:42:33
2024-11-23 16:57:34.900 Please replace `st.experimental_get_query_params` with `st.query_params`.

`st.experimental_get_query_params` will be removed after 2024-04-11.

Refer to our [docs page](https://docs.streamlit.io/develop/api-reference/caching-and-state/st.query_params) for more information.
2024-11-23 16:57:37.678 Please replace `st.experimental_get_query_params` with `st.query_params`.

`st.experimental_get_query_params` will be removed after 2024-04-11.

Refer to our [docs page](https://docs.streamlit.io/develop/api-reference/caching-and-state/st.query_params) for more information.
2024-11-23 16:57:46.959 Please replace `st.experimental_get_query_params` with `st.query_params`.

`st.experimental_get_query_params` will be removed after 2024-04-11.

Refer to our [docs page](https://docs.streamlit.io/develop/api-reference/caching-and-state/st.query_params) for more information.
2024-11-23 16:57:46.961 Please replace `st.experimental_get_query_params` with `st.query_params`.

`st.experimental_get_query_params` will be removed after 2024-04-11.

Refer to our [docs page](https://docs.streamlit.io/develop/api-reference/caching-and-state/st.query_params) for more information.
2024-11-23 16:57:46.962 Uncaught app exception
Traceback (most recent call last):
  File "F:\course work\slash-phase6\.venv\lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
  File "F:\course work\slash-phase6\.venv\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 579, in code_to_exec
    exec(code, module.__dict__)
  File "F:\course work\slash-phase6\slash_user_interface.py", line 34, in <module>
    google_callback()
  File "F:\course work\slash-phase6\slash_user_interface.py", line 27, in google_callback
    token = google.fetch_token(token_url, client_secret=client_secret, authorization_response=st.experimental_get_query_params()['code'][0])
  File "F:\course work\slash-phase6\.venv\lib\site-packages\requests_oauthlib\oauth2_session.py", line 271, in fetch_token
    self._client.parse_request_uri_response(
  File "F:\course work\slash-phase6\.venv\lib\site-packages\oauthlib\oauth2\rfc6749\clients\web_application.py", line 220, in parse_request_uri_response
    response = parse_authorization_code_response(uri, state=state)
  File "F:\course work\slash-phase6\.venv\lib\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 272, in parse_authorization_code_response
    raise InsecureTransportError()
oauthlib.oauth2.rfc6749.errors.InsecureTransportError: (insecure_transport) OAuth 2 MUST utilize https.

**Comment by YinanWusoymilk** [comment]
This error occurs because the OAuth 2.0 specification requires the use of HTTPS instead of HTTP. To test in a local development environment, you can use the InsecureTransportError to ignore this error, but this is only recommended for development environments and not in production.

To ignore this error in a local development environment, you can use the following code:

Import InsecureTransportError and ignore it:

def google_callback():
    try:
        google = OAuth2Session(client_id, redirect_uri=redirect_uri, scope=['openid', 'email', 'profile'])
        token = google.fetch_token(token_url, client_secret=client_secret, authorization_response=st.query_params['code'][0], verify=False)
        user_info = google.get('https://www.googleapis.com/oauth2/v1/userinfo').json()
        st.session_state.token = token
        st.session_state.user_info = user_info
        st.experimental_rerun()
    except InsecureTransportError:
        st.error("OAuth 2.0 requires HTTPS. Please use HTTPS in production.")

if 'code' in st.query_params:
    google_callback()
